# Split the dataset into 2 parts

1 smaller part will be used for tuning, the other one for evaluation of the tuned algorithms.


In [1]:
import os
os.chdir("../..")
os.getcwd()

'/Users/sbokupripeku/git/work/examples/costly_nonstationary_bandits'

In [2]:
%load_ext autoreload
%autoreload 2

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time
import pickle

from src import algorithms
from src import evaluation
from src import costs
from src.plotting.costs import plot_costs

In [3]:
np.random.seed(42)

In [4]:
csv_file = 'experiments/nursery/nursery.csv'

In [5]:
df = pd.read_csv(csv_file)

In [6]:
df

parents   has_nurs      form children     housing     finance  \
0           usual     proper  complete        1  convenient  convenient   
1           usual     proper  complete        1  convenient  convenient   
2           usual     proper  complete        1  convenient  convenient   
3           usual     proper  complete        1  convenient  convenient   
4           usual     proper  complete        1  convenient  convenient   
...           ...        ...       ...      ...         ...         ...   
12955  great_pret  very_crit    foster     more    critical      inconv   
12956  great_pret  very_crit    foster     more    critical      inconv   
12957  great_pret  very_crit    foster     more    critical      inconv   
12958  great_pret  very_crit    foster     more    critical      inconv   
12959  great_pret  very_crit    foster     more    critical      inconv   

              social       health final evaluation  
0            nonprob  recommended        recommend  
1            nonprob     priority         priority  
2            nonprob    not_recom        not_recom  
3      slightly_prob  recommended        recommend  
4      slightly_prob     priority         priority  
...              ...          ...              ...  
12955  slightly_prob     priority       spec_prior  
12956  slightly_prob    not_recom        not_recom  
12957    problematic  recommended       spec_prior  
12958    problematic     priority       spec_prior  
12959    problematic    not_recom        not_recom  

[12960 rows x 9 columns]

In [7]:
df_num = df.astype('category')

In [8]:
df_num['final evaluation']

0         recommend
1          priority
2         not_recom
3         recommend
4          priority
            ...    
12955    spec_prior
12956     not_recom
12957    spec_prior
12958    spec_prior
12959     not_recom
Name: final evaluation, Length: 12960, dtype: category
Categories (5, object): ['not_recom', 'priority', 'recommend', 'spec_prior', 'very_recom']

In [9]:
# Order categories correctly, because order has meaning.
df_num.parents = df_num.parents.cat.reorder_categories(['usual', 'pretentious', 'great_pret'])
df_num.has_nurs = df_num.has_nurs.cat.reorder_categories(
    ['proper', 'less_proper',  'improper', 'critical', 'very_crit']
)
df_num.form = df_num.form.cat.reorder_categories(['complete', 'completed', 'incomplete', 'foster'])
df_num.children = df_num.children.cat.reorder_categories(['1', '2', '3', 'more'])
df_num.housing = df_num.housing.cat.reorder_categories(['convenient', 'less_conv', 'critical'])
df_num.finance = df_num.finance.cat.reorder_categories(['convenient', 'inconv'])
df_num.social = df_num.social.cat.reorder_categories(['nonprob', 'slightly_prob', 'problematic'])
df_num.health = df_num.health.cat.reorder_categories(['not_recom', 'recommended', 'priority'])
df_num['final evaluation'] = df_num['final evaluation'].cat.reorder_categories(
    ['not_recom', 'recommend',  'very_recom', 'priority', 'spec_prior',]
)


In [10]:
df_num

parents   has_nurs      form children     housing     finance  \
0           usual     proper  complete        1  convenient  convenient   
1           usual     proper  complete        1  convenient  convenient   
2           usual     proper  complete        1  convenient  convenient   
3           usual     proper  complete        1  convenient  convenient   
4           usual     proper  complete        1  convenient  convenient   
...           ...        ...       ...      ...         ...         ...   
12955  great_pret  very_crit    foster     more    critical      inconv   
12956  great_pret  very_crit    foster     more    critical      inconv   
12957  great_pret  very_crit    foster     more    critical      inconv   
12958  great_pret  very_crit    foster     more    critical      inconv   
12959  great_pret  very_crit    foster     more    critical      inconv   

              social       health final evaluation  
0            nonprob  recommended        recommend  
1            nonprob     priority         priority  
2            nonprob    not_recom        not_recom  
3      slightly_prob  recommended        recommend  
4      slightly_prob     priority         priority  
...              ...          ...              ...  
12955  slightly_prob     priority       spec_prior  
12956  slightly_prob    not_recom        not_recom  
12957    problematic  recommended       spec_prior  
12958    problematic     priority       spec_prior  
12959    problematic    not_recom        not_recom  

[12960 rows x 9 columns]

In [11]:
for colname in df:
    df_num[colname] = df_num[colname].cat.codes + 1

In [12]:
df_num

parents  has_nurs  form  children  housing  finance  social  health  \
0            1         1     1         1        1        1       1       2   
1            1         1     1         1        1        1       1       3   
2            1         1     1         1        1        1       1       1   
3            1         1     1         1        1        1       2       2   
4            1         1     1         1        1        1       2       3   
...        ...       ...   ...       ...      ...      ...     ...     ...   
12955        3         5     4         4        3        2       2       3   
12956        3         5     4         4        3        2       2       1   
12957        3         5     4         4        3        2       3       2   
12958        3         5     4         4        3        2       3       3   
12959        3         5     4         4        3        2       3       1   

       final evaluation  
0                     2  
1                     4  
2                     1  
3                     2  
4                     4  
...                 ...  
12955                 5  
12956                 1  
12957                 5  
12958                 5  
12959                 1  

[12960 rows x 9 columns]

In [13]:
# Features are dropped according to their usefulness for the linear regression model.
# final evaluation is target variable

all_contexts = df_num.drop(['parents', 'has_nurs', 'social', 'social', 'final evaluation'], axis=1)

# For debug and testing drop some more columns
# all_contexts = all_contexts.drop(['form'], axis=1).to_numpy()
# all_contexts = all_contexts.drop(['finance', 'form'], axis=1).to_numpy()

In [14]:
all_contexts.shape

(12960, 5)

In [15]:
all_contexts

form  children  housing  finance  health
0         1         1        1        1       2
1         1         1        1        1       3
2         1         1        1        1       1
3         1         1        1        1       2
4         1         1        1        1       3
...     ...       ...      ...      ...     ...
12955     4         4        3        2       3
12956     4         4        3        2       1
12957     4         4        3        2       2
12958     4         4        3        2       3
12959     4         4        3        2       1

[12960 rows x 5 columns]

In [16]:
y = df_num['final evaluation']

In [17]:
y.value_counts()

1    4320
4    4266
5    4044
3     328
2       2
Name: final evaluation, dtype: int64

In [18]:
# Drop arms with small rewards

In [19]:
# Values meaning:
# not recommended (1)
# recommend (2)
# very recommend (3)
# priority acceptance (4)
# special priority (5)

In [20]:
(y != 3) & (y != 2)

0        False
1         True
2         True
3        False
4         True
         ...  
12955     True
12956     True
12957     True
12958     True
12959     True
Name: final evaluation, Length: 12960, dtype: bool

In [21]:
all_contexts = all_contexts[(y != 3) & (y != 2)]

In [22]:
y = y[(y != 3) & (y != 2)]

In [23]:
y.value_counts()

1    4320
4    4266
5    4044
Name: final evaluation, dtype: int64

In [24]:
np.sum(np.where(y == 3, 1, 0))

0

In [25]:
unique = np.unique(y)
all_rewards = np.zeros((y.shape[0], len(unique)))
for n_arm, y_value in enumerate(unique):
    all_rewards[:, n_arm] = np.where(y == y_value, 1, 0)
    

In [26]:
all_rewards

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [27]:
np.array(np.sum(all_rewards, axis=0), dtype=int)

array([4320, 4266, 4044])

# Split dataset into tuning and evaluation parts

In [28]:
TUNING_SIZE = 2630

In [29]:
all_contexts.head()

form  children  housing  finance  health
1     1         1        1        1       3
2     1         1        1        1       1
4     1         1        1        1       3
5     1         1        1        1       1
6     1         1        1        1       2

In [30]:
tuning_idx = np.random.choice(a=all_contexts.shape[0], replace=False, size=TUNING_SIZE)
tuning_idx.sort()

In [31]:
tuning_idx

array([    0,     3,     8, ..., 12624, 12628, 12629])

In [32]:
tng_idx_set = set(tuning_idx)

In [33]:
evaluation_idx = np.array([i for i in range(all_contexts.shape[0]) if i not in tng_idx_set])

In [34]:
contexts_tuning = all_contexts.iloc[tuning_idx, :]

In [35]:
contexts_evaluation= all_contexts.iloc[evaluation_idx, :]

In [36]:
contexts_tuning

form  children  housing  finance  health
1         1         1        1        1       3
5         1         1        1        1       1
11        1         1        1        2       1
19        1         1        2        1       3
23        1         1        2        1       1
...     ...       ...      ...      ...     ...
12947     4         4        3        1       1
12951     4         4        3        2       2
12954     4         4        3        2       2
12958     4         4        3        2       3
12959     4         4        3        2       1

[2630 rows x 5 columns]

In [37]:
contexts_evaluation

form  children  housing  finance  health
2         1         1        1        1       1
4         1         1        1        1       3
6         1         1        1        1       2
7         1         1        1        1       3
8         1         1        1        1       1
...     ...       ...      ...      ...     ...
12952     4         4        3        2       3
12953     4         4        3        2       1
12955     4         4        3        2       3
12956     4         4        3        2       1
12957     4         4        3        2       2

[10000 rows x 5 columns]

In [38]:
rewards_tuning = all_rewards[tuning_idx, :]

In [39]:
rewards_evaluation = all_rewards[evaluation_idx, :]

In [40]:
rewards_tuning.shape, rewards_evaluation.shape

((2630, 3), (10000, 3))

## Save the data

In [41]:
with open('dataset/nursery/nursery_tuning.pickle', 'wb') as f:
    pickle.dump(
        (contexts_tuning, rewards_tuning),
        f
    )

In [42]:
with open('dataset/nursery/nursery_evaluation.pickle', 'wb') as f:
    pickle.dump(
        (contexts_evaluation, rewards_evaluation),
        f
    )